export const REQUEST_CART_ITEM = "REQUEST_CART_ITEM";
export const GET_CART_ITEM = "GET_CART_ITEM";
export const ERROR_CART_ITEM = "ERROR_CART_ITEM";

// for delete
export const DELETE_REQUEST_CART_ITEM = "DELETE_REQUEST_CART_ITEM";
export const DELETE_GET_CART_ITEM = "DELETE_GET_CART_ITEM";
export const DELETE_ERROR_CART_ITEM = "DELETE_ERROR_CART_ITEM";