export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_ERROR = "GET_DATA_ERROR";
//mens
export const GET_MENS_DATA_SUCESS = "GET_MENS_DATA_SUCESS";
//womens
export const GET_WOMENS_DATA_SUCESS = "GET_WOMENS_DATA_SUCESS";
//Accessories
export const GET_ACCESSORIES_DATA_SUCESS = "GET_ACCESSORIES_DATA_SUCESS";
